### PR TITLE
feature/7-allow-empty-config

### LINKED ISSUE #7: Allow empty config files
## Hacktoberfest 2021 PHP issue

Right now there's a bug if a config file is empty, when using `loadFile()` or `loadDir()` - it throws an exception like this:
```
PHP Fatal error:  Uncaught TypeError: xy2z\LiteConfig\LiteConfig::loadArray(): Argument #1 ($data) must be of type array, null given
```

Allow config files to be empty, with no returned data.

You can use this code to reproduce the bug. But first create 3 empty files in a config dir as seen below:
```php
<?php

require __DIR__ . '/src/LiteConfig.php';

use xy2z\LiteConfig\Liteconfig;

LiteConfig::loadFile(__DIR__ . '/config/empty.ini');
LiteConfig::loadFile(__DIR__ . '/config/empty.json');
LiteConfig::loadFile(__DIR__ . '/config/empty.php');
LiteConfig::loadDir(__DIR__ . '/config');

var_dump(LiteConfig::all());
```

Let me know if you have questions.

### PR DESCRIPTION
**Pull request by bstuff**
fixes #7

### CODE REVIEW

**Comment by xy2z** [comment]
Thanks!

This works from my testing, but to also handle custom_handler's and possible future formats i think a better fix would be to do a check in the loadFile() function:

```phph
        // Load file content
        $content = static::getFileContent($path, $pathinfo);
        static::loadArray($content, $prefix);
```

**Comment by xy2z** [comment]
@bstuff ^

**Comment by bstuff** [comment]
> @bstuff ^

Ok I'll try today ✌️

**Comment by bstuff** [comment]
@xy2z please review

**Comment by xy2z** [comment]
@bstuff

Just 2 small changes and its done.
Sorry I know it's partly my fault for not having enough tests but I will look into that soon

**Pull request closed without merging**
